# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dktz9_MR4rbwPK_eSrqs_8--idunrlVT
"""

import tensorflow as tf
import tensorflow_datasets as tfds

data_dir = '/content/drive/MyDrive/MAESTRIA USP/6. DATA'

from google.colab import drive
drive.mount('/content/drive')

import os
# Verifica si existe
print("Existe carpeta:", os.path.isdir(data_dir))
print("Subcarpetas:", os.listdir(data_dir))

img_width, img_height = 224, 224
batch_size = 32

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_dir = '/content/drive/MyDrive/MAESTRIA USP/6. DATA/training_set'
val_dir = '/content/drive/MyDrive/MAESTRIA USP/6. DATA/validation_set'
test_dir = '/content/drive/MyDrive/MAESTRIA USP/6. DATA/test_set'

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,       # rotaciones aleatorias
    width_shift_range=0.1,   # desplazamiento horizontal
    height_shift_range=0.1,  # desplazamiento vertical
    shear_range=0.1,         # transformaciones de corte
    zoom_range=0.1,          # zoom aleatorio
    horizontal_flip=True,    # voltear horizontalmente
    brightness_range=[0.8, 1.2] # variaciones de brillo
)

val_test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),  # Ajusta según el tamaño de tus imágenes
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=False
)

val_generator = val_test_datagen.flow_from_directory(
    val_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=False
)

test_generator = val_test_datagen.flow_from_directory(
    test_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=False
)

import matplotlib.pyplot as plt

# Visualizar un lote de imágenes y sus etiquetas desde el generador
images, labels = next(train_generator)

plt.figure(figsize=(10, 10))
for i in range(min(25, len(images))):  # Muestra hasta 25 imágenes
    ax = plt.subplot(5, 5, i + 1)
    plt.imshow(images[i])
    label_index = labels[i].argmax()
    class_label = list(train_generator.class_indices.keys())[label_index]
    plt.title(class_label)
    plt.axis("off")

plt.tight_layout()
plt.show()

#Crear extractor de características

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

x = base_model.output
x = GlobalAveragePooling2D()(x)

feature_extractor = Model(inputs=base_model.input, outputs=x)

#Extraer características

import numpy as np

def extract_features(generator):

    features = []
    labels = []

    for images, lbls in generator:
        feats = feature_extractor.predict(images)
        features.append(feats)
        labels.append(lbls)

        if len(features)*batch_size >= generator.samples:
            break

    features = np.vstack(features)
    labels = np.vstack(labels)

    return features, np.argmax(labels, axis=1)

#Aplicar extracción

X_train, y_train = extract_features(train_generator)
X_val, y_val = extract_features(val_generator)
X_test, y_test = extract_features(test_generator)

#Entrenar SVM

from sklearn.svm import SVC

svm = SVC(kernel='rbf', probability=True)

svm.fit(X_train, y_train)

#Evaluación

from sklearn.metrics import classification_report

y_pred = svm.predict(X_test)

print(classification_report(
    y_test,
    y_pred,
    target_names=list(train_generator.class_indices.keys())
))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=train_generator.class_indices.keys(),
            yticklabels=train_generator.class_indices.keys())

plt.xlabel("Predicción")
plt.ylabel("Etiqueta Real")
plt.title("Matriz de Confusión - MobileNetV2 + SVM")
plt.show()

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
import numpy as np
import matplotlib.pyplot as plt

# Número de clases
n_classes = len(train_generator.class_indices)

# Binarizar etiquetas reales
y_test_bin = label_binarize(y_test, classes=np.arange(n_classes))

# Obtener probabilidades del modelo
y_score = svm.predict_proba(X_test)

# Calcular ROC y AUC para cada clase
fpr = dict()
tpr = dict()
roc_auc = dict()

for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Calcular ROC macro-promedio
all_fpr = np.unique(np.concatenate([fpr[i] for i in range(n_classes)]))

mean_tpr = np.zeros_like(all_fpr)
for i in range(n_classes):
    mean_tpr += np.interp(all_fpr, fpr[i], tpr[i])

mean_tpr /= n_classes

roc_auc_macro = auc(all_fpr, mean_tpr)

# Graficar
plt.figure(figsize=(8,6))

for i, class_name in enumerate(train_generator.class_indices.keys()):
    plt.plot(fpr[i], tpr[i], label=f"{class_name} (AUC = {roc_auc[i]:.2f})")

plt.plot(all_fpr, mean_tpr, linestyle='--', label=f"Macro-average (AUC = {roc_auc_macro:.2f})")

plt.plot([0,1], [0,1], 'k--')
plt.xlabel("Tasa de Falsos Positivos (FPR)")
plt.ylabel("Tasa de Verdaderos Positivos (TPR)")
plt.title("Curva ROC Multiclase - MobileNetV2 + SVM")
plt.legend()
plt.show()

from sklearn.metrics import precision_recall_curve, average_precision_score

precision = dict()
recall = dict()
ap = dict()

for i in range(n_classes):
    precision[i], recall[i], _ = precision_recall_curve(y_test_bin[:, i], y_score[:, i])
    ap[i] = average_precision_score(y_test_bin[:, i], y_score[:, i])

# Macro promedio AP
ap_macro = np.mean(list(ap.values()))

# Gráfico
plt.figure(figsize=(8,6))

for i, class_name in enumerate(train_generator.class_indices.keys()):
    plt.plot(recall[i], precision[i], label=f"{class_name} (AP={ap[i]:.2f})")

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Multiclase - MobileNetV2 + SVM")
plt.legend()
plt.show()

print("Average Precision Macro:", round(ap_macro, 3))