# -*- coding: utf-8 -*-
"""TCC_MobileNetV2_congelado_modelo_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10XXQukEeQGnZGyfwkfgY0IOKs6KUVWjS
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import random
import numpy as np

SEED = 42

# Python
random.seed(SEED)

# NumPy
np.random.seed(SEED)

# TensorFlow
tf.random.set_seed(SEED)

data_dir = '/content/drive/MyDrive/MAESTRIA USP/6. DATA'

from google.colab import drive
drive.mount('/content/drive')

import os
# Verifica si existe
print("Existe carpeta:", os.path.isdir(data_dir))
print("Subcarpetas:", os.listdir(data_dir))

img_width, img_height = 224, 224
batch_size = 32

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_dir = '/content/drive/MyDrive/MAESTRIA USP/6. DATA/training_set'
val_dir = '/content/drive/MyDrive/MAESTRIA USP/6. DATA/validation_set'
test_dir = '/content/drive/MyDrive/MAESTRIA USP/6. DATA/test_set'

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,       # rotaciones aleatorias
    width_shift_range=0.1,   # desplazamiento horizontal
    height_shift_range=0.1,  # desplazamiento vertical
    shear_range=0.1,         # transformaciones de corte
    zoom_range=0.1,          # zoom aleatorio
    horizontal_flip=True,    # voltear horizontalmente
    brightness_range=[0.8, 1.2] # variaciones de brillo
)

val_test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),  # Ajusta según el tamaño de tus imágenes
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=True,
    seed=SEED
)

val_generator = val_test_datagen.flow_from_directory(
    val_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=True,
    seed=SEED
)

test_generator = val_test_datagen.flow_from_directory(
    test_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=False
)

import matplotlib.pyplot as plt

# Visualizar un lote de imágenes y sus etiquetas desde el generador
images, labels = next(train_generator)

plt.figure(figsize=(10, 10))
for i in range(min(25, len(images))):  # Muestra hasta 25 imágenes
    ax = plt.subplot(5, 5, i + 1)
    plt.imshow(images[i])
    label_index = labels[i].argmax()
    class_label = list(train_generator.class_indices.keys())[label_index]
    plt.title(class_label)
    plt.axis("off")

plt.tight_layout()
plt.show()

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

# Congelar todas las capas
base_model.trainable = False

model_tl = models.Sequential([

    base_model,

    layers.GlobalAveragePooling2D(),

    layers.Dense(128, activation='relu'),

    layers.Dropout(0.5),

    layers.Dense(train_generator.num_classes, activation='softmax')

])

model_tl.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model_tl.summary()

#Early stopping

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history_tl = model_tl.fit(
    train_generator,
    validation_data=val_generator,
    epochs=30,
    callbacks=[early_stop]
)

#Evaluación final en Test

#Los generadores de Keras guardan estado interno, por lo que antes de evaluar es recomendable hacer un reset
test_generator.reset()

#Evaluación final en Test
test_loss, test_acc = model_tl.evaluate(test_generator)

print("Precisión final en test:", test_acc)

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

test_generator.reset()

predictions = model_tl.predict(test_generator)

y_pred = np.argmax(predictions, axis=1)
y_test = test_generator.classes

cm = confusion_matrix(y_test, y_pred)

class_names = list(train_generator.class_indices.keys())

plt.figure(figsize=(8,6))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)

plt.xlabel("Predicción")
plt.ylabel("Etiqueta Real")
plt.title("Matriz de Confusión - MobileNetV2")
plt.show()

from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    y_pred,
    target_names=class_names
))

plt.plot(history_tl.history['accuracy'], label='Precisión del entrenamiento')
plt.plot(history_tl.history['val_accuracy'], label='Precisión de la validación')

plt.title('Precisión del modelo MobileNetV2')
plt.xlabel('Epocas')
plt.ylabel('Precisión')
plt.legend()
plt.show()